include:
- ./../../configs/hw/cortexm_memory.yml
- ./syms.yml

memory_map:
  mmio_GPIO_USB_CRC_SCTIMER_PWM:
    base_addr: 0x1c000000
    permissions: rw
    size: 0x28000
  sram:
    base_addr: 0x2000000
    permissions: rwx
    size: 0x8000
  text:
    base_addr: 0x0
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
    is_entry: True

use_nvic: false
use_timers: false
use_systick: false
